/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface MetadataValidatorInterface extends utils.Interface {
  contractName: "MetadataValidator";
  functions: {
    "validateMetadata(address,string,uint256,uint256,bytes,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "validateMetadata",
    values: [string, string, BigNumberish, BigNumberish, BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "validateMetadata",
    data: BytesLike
  ): Result;

  events: {};
}

export interface MetadataValidator extends BaseContract {
  contractName: "MetadataValidator";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MetadataValidatorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    validateMetadata(
      ownerEthAddress: string,
      newJSONMeta: string,
      additionStartIndex: BigNumberish,
      additionEndIndex: BigNumberish,
      ownerSignature: BytesLike,
      sender: string,
      overrides?: CallOverrides
    ): Promise<[string, string]>;
  };

  validateMetadata(
    ownerEthAddress: string,
    newJSONMeta: string,
    additionStartIndex: BigNumberish,
    additionEndIndex: BigNumberish,
    ownerSignature: BytesLike,
    sender: string,
    overrides?: CallOverrides
  ): Promise<[string, string]>;

  callStatic: {
    validateMetadata(
      ownerEthAddress: string,
      newJSONMeta: string,
      additionStartIndex: BigNumberish,
      additionEndIndex: BigNumberish,
      ownerSignature: BytesLike,
      sender: string,
      overrides?: CallOverrides
    ): Promise<[string, string]>;
  };

  filters: {};

  estimateGas: {
    validateMetadata(
      ownerEthAddress: string,
      newJSONMeta: string,
      additionStartIndex: BigNumberish,
      additionEndIndex: BigNumberish,
      ownerSignature: BytesLike,
      sender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    validateMetadata(
      ownerEthAddress: string,
      newJSONMeta: string,
      additionStartIndex: BigNumberish,
      additionEndIndex: BigNumberish,
      ownerSignature: BytesLike,
      sender: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
